# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'currencyConverter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for currencyConverter
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'R.swift'
  pod 'Alamofire'
  pod "CDAlertView"
  pod 'RealmSwift'

  target 'currencyConverterTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
    pod 'Quick'
    pod 'Nimble'
  end

  target 'currencyConverterUITests' do
    # Pods for testing
  end

end
